from .prompts import (
    ZEROSHOT_ACT_INSTRUCTION,
    ZEROSHOT_REACT_INSTRUCTION,
    ZEROSHOT_REACT_INSTRUCTION_GLM4,
    ONESHOT_REACT_INSTRUCTION,
    ONESHOT_REACT_INSTRUCTION_GLM4,
    DIRECT_PROMPT,
)

__all__ = [
    "ZEROSHOT_ACT_INSTRUCTION",
    "ZEROSHOT_REACT_INSTRUCTION",
    "ZEROSHOT_REACT_INSTRUCTION_GLM4",
    "ONESHOT_REACT_INSTRUCTION",
    "ONESHOT_REACT_INSTRUCTION_GLM4",
    "DIRECT_PROMPT",
]
